from app.dynamo.tables import (
    USERS, SELLERS, EMAIL_OTPS, MARKETPLACE_ACCOUNTS,
    SYNC_RUNS, ORDERS, ORDER_ITEMS, INVENTORY_SNAPSHOTS,
    PRICE_SNAPSHOTS, PRODUCT_MASTER, LISTING_MAP,
    CUSTOMER_REVIEWS, REVIEW_INSIGHTS, DEMAND_FORECASTS,
    PRICING_RECOMMENDATIONS, CHAT_SESSIONS, CHAT_MESSAGES,
    AI_REPORTS,
)
